export const API_REQUEST_ISREQUESTING = 'API_REQUEST_ISREQUESTING';
export const API_REQUEST_FAIL = 'API_REQUEST_FAIL';

// LIST CONSTANTS
export const LIST_ACTION_REQUESTED = 'LIST_ACTION_REQUESTED';
export const LIST_ACTION_SUCCEDED = 'LIST_ACTION_SUCCEDED';
export const LIST_ACTION_FAILED = 'LIST_ACTION_FAILED';
export const LIST_ACTION_CLEAR = 'LIST_ACTION_CLEAR';
export const LIST_ACTION_ADD = 'LIST_ACTION_ADD';
export const LIST_ACTION_EDIT = 'LIST_ACTION_EDIT';
export const LIST_ACTION_DELETE = 'LIST_ACTION_DELETE';

// MODAL CONSTANTS
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';